/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author Nasa
 */
public class frmacerca extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmacerca
     */
    public void posicionVentana() {
        int x = frmprincipal.jDesktopPane1.getWidth() - this.getWidth();
        int y = frmprincipal.jDesktopPane1.getHeight() - this.getHeight();
        x = x / 2;
        y = y / 2;
        
        this.setLocation(x, y);
    }

    public frmacerca() {
        initComponents();
        setVisible(true);
        posicionVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblprincipal = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ACERCA DE ..");
        setToolTipText("");

        lblprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/draw_acerca_total.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblprincipal;
    // End of variables declaration//GEN-END:variables
}
