package vista;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class frmagradecimiento extends javax.swing.JInternalFrame {

    public Clip clip;
    public String ruta = "/img/";

    public void posicionVentana() {
        int x = frmprincipal.jDesktopPane1.getWidth() - this.getWidth();
        int y = frmprincipal.jDesktopPane1.getHeight() - this.getHeight();
        x = x / 2;
        y = y / 2;

        this.setLocation(x, y);
    }

    public void sonido(String archivo) {
        try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav")));
            clip.start();
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

    }

    public frmagradecimiento() {
        initComponents();
        setVisible(true);
        posicionVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblprincipalagradecer = new javax.swing.JLabel();

        setClosable(true);
        setTitle("AGRADECIMIENTO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblprincipalagradecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/draw_ceo.jpg"))); // NOI18N
        lblprincipalagradecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblprincipalagradecerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprincipalagradecer, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprincipalagradecer, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblprincipalagradecerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprincipalagradecerMousePressed
            sonido("audio_presentacion");
    }//GEN-LAST:event_lblprincipalagradecerMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblprincipalagradecer;
    // End of variables declaration//GEN-END:variables
}
