/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import apps.Niveles;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author lfcontreras
 */
public class frmjuegoniveles extends javax.swing.JFrame implements KeyListener {

    frmpaneljuego pa = new frmpaneljuego();
    String letras;

    public void rePintarLabel() {
        btn1.setText(String.valueOf(this.letras.charAt(0)));
        btn2.setText(String.valueOf(this.letras.charAt(1)));
        btn3.setText(String.valueOf(this.letras.charAt(2)));
        btn4.setText(String.valueOf(this.letras.charAt(3)));
    }

    public String BotonSeleccionado(String letra) {
        String button;
        if ("Desconocido".equals(letra)) {
            button = "btn" + "N2";
        } else {
            button = "btn" + letra + "1";
        }

        return button;
    }

    public void saberNiveles(Niveles a) {
        switch (a) {
            case NIVEL1:
                letras = "ffjj";
                break;
            case NIVEL2:
                letras = "dkdk";
                break;
            case NIVEL3:
                letras = "slsl";
                break;
            case NIVEL4:
                letras = "ajaj";
                break;
            case NIVEL5:
                letras = "skks";
                break;
            case NIVEL6:
                letras = "dldl";
                break;
            case NIVEL7:
                letras = "ahha";
                break;
            case NIVEL8:
                letras = "flfl";
                break;
        }
    }

    public frmjuegoniveles(Niveles a) {
        saberNiveles(a);
        initComponents();
        rePintarLabel();
        setVisible(true);
        setLocationRelativeTo(null);
        jpanelTeclado.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanelTeclado = new javax.swing.JPanel();
        btnS1 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnJ1 = new javax.swing.JButton();
        btnK1 = new javax.swing.JButton();
        btnL1 = new javax.swing.JButton();
        btnN2 = new javax.swing.JButton();
        btnZ1 = new javax.swing.JButton();
        btnX1 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnV1 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnN1 = new javax.swing.JButton();
        btnM1 = new javax.swing.JButton();
        btnQ1 = new javax.swing.JButton();
        btnW1 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnR1 = new javax.swing.JButton();
        btnT1 = new javax.swing.JButton();
        btnY1 = new javax.swing.JButton();
        btnU1 = new javax.swing.JButton();
        btnI1 = new javax.swing.JButton();
        btnO1 = new javax.swing.JButton();
        btnP1 = new javax.swing.JButton();
        btnSpace1 = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FASE DEL FUEGO");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jpanelTeclado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpanelTecladoKeyPressed(evt);
            }
        });

        btnS1.setBackground(new java.awt.Color(255, 255, 255));
        btnS1.setText("S");

        btnF1.setBackground(new java.awt.Color(255, 255, 255));
        btnF1.setText("F");

        btnG1.setBackground(new java.awt.Color(255, 255, 255));
        btnG1.setText("G");

        btnD1.setBackground(new java.awt.Color(255, 255, 255));
        btnD1.setText("D");

        btnA1.setBackground(new java.awt.Color(255, 255, 255));
        btnA1.setText("A");

        btnH1.setBackground(new java.awt.Color(255, 255, 255));
        btnH1.setText("H");

        btnJ1.setBackground(new java.awt.Color(255, 255, 255));
        btnJ1.setText("J");

        btnK1.setBackground(new java.awt.Color(255, 255, 255));
        btnK1.setText("K");

        btnL1.setBackground(new java.awt.Color(255, 255, 255));
        btnL1.setText("L");

        btnN2.setBackground(new java.awt.Color(255, 255, 255));
        btnN2.setText("Ñ");

        btnZ1.setBackground(new java.awt.Color(255, 255, 255));
        btnZ1.setText("Z");

        btnX1.setBackground(new java.awt.Color(255, 255, 255));
        btnX1.setText("X");

        btnC1.setBackground(new java.awt.Color(255, 255, 255));
        btnC1.setText("C");

        btnV1.setBackground(new java.awt.Color(255, 255, 255));
        btnV1.setText("V");

        btnB1.setBackground(new java.awt.Color(255, 255, 255));
        btnB1.setText("B");

        btnN1.setBackground(new java.awt.Color(255, 255, 255));
        btnN1.setText("N");

        btnM1.setBackground(new java.awt.Color(255, 255, 255));
        btnM1.setText("M");

        btnQ1.setBackground(new java.awt.Color(255, 255, 255));
        btnQ1.setText("Q");

        btnW1.setBackground(new java.awt.Color(255, 255, 255));
        btnW1.setText("W");

        btnE1.setBackground(new java.awt.Color(255, 255, 255));
        btnE1.setText("E");

        btnR1.setBackground(new java.awt.Color(255, 255, 255));
        btnR1.setText("R");

        btnT1.setBackground(new java.awt.Color(255, 255, 255));
        btnT1.setText("T");

        btnY1.setBackground(new java.awt.Color(255, 255, 255));
        btnY1.setText("Y");

        btnU1.setBackground(new java.awt.Color(255, 255, 255));
        btnU1.setText("U");

        btnI1.setBackground(new java.awt.Color(255, 255, 255));
        btnI1.setText("I");

        btnO1.setBackground(new java.awt.Color(255, 255, 255));
        btnO1.setText("O");

        btnP1.setBackground(new java.awt.Color(255, 255, 255));
        btnP1.setText("P");

        btnSpace1.setText("space");

        javax.swing.GroupLayout jpanelTecladoLayout = new javax.swing.GroupLayout(jpanelTeclado);
        jpanelTeclado.setLayout(jpanelTecladoLayout);
        jpanelTecladoLayout.setHorizontalGroup(
            jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelTecladoLayout.createSequentialGroup()
                        .addComponent(btnQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnW1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnE1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnR1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnU1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnI1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnO1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelTecladoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnS1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnH1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnK1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnL1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnN2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelTecladoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelTecladoLayout.createSequentialGroup()
                                .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnV1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnN1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jpanelTecladoLayout.setVerticalGroup(
            jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnR1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnW1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnO1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnU1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnI1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnS1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnL1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnK1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnH1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnV1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpanelTeclado);
        jpanelTeclado.setBounds(150, 180, 580, 248);

        btnsalir.setText("SALIR");
        btnsalir.setOpaque(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir);
        btnsalir.setBounds(40, 250, 80, 50);

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("J");
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn2KeyPressed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(280, 60, 100, 80);

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("J");
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn3KeyPressed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(400, 60, 100, 80);

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("J");
        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn4KeyPressed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(520, 60, 100, 80);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("J");
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn1KeyPressed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(160, 60, 100, 80);

        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner_nivel.jpg"))); // NOI18N
        jPanel1.add(lblimagen);
        lblimagen.setBounds(0, 0, 780, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(770, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        int resp = JOptionPane.showConfirmDialog(null, "¿Estas Seguro a salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            this.dispose();
        } else {
            this.dispose();
            frmprincipal.jDesktopPane1.add(pa);
            pa.moveToFront();
        }


    }//GEN-LAST:event_btnsalirActionPerformed

    private void btn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyPressed

        try {
            if (evt.getKeyChar() == this.letras.charAt(0)) {
                btn1.setBackground(Color.GREEN);
                btn1.setEnabled(false);
            } else {
                btn1.setBackground(Color.RED);
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn1KeyPressed

    private void btn2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyPressed
        try {
            if (evt.getKeyChar() == this.letras.charAt(1)) {
                btn2.setBackground(Color.GREEN);
                btn2.setEnabled(false);
            } else {
                btn2.setBackground(Color.RED);
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn2KeyPressed

    private void btn3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyPressed
        try {
            if (evt.getKeyChar() == this.letras.charAt(2)) {
                btn3.setBackground(Color.GREEN);
                btn3.setEnabled(false);
            } else {
                btn3.setBackground(Color.RED);
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn3KeyPressed

    private void btn4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn4KeyPressed
        try {
            if (evt.getKeyChar() == this.letras.charAt(3)) {
                btn4.setBackground(Color.GREEN);
                btn4.setEnabled(false);
                JOptionPane.showMessageDialog(null, "FELICITACIONES LOGRASTES PASAR EXITOSAMENTE ESTE NIVEL");
                this.dispose();

                frmprincipal.jDesktopPane1.add(pa);
                pa.moveToFront();

            } else {
                btn4.setBackground(Color.RED);
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn4KeyPressed

    private void jpanelTecladoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpanelTecladoKeyPressed
        String Entrada = KeyEvent.getKeyText(evt.getKeyCode());

        System.out.println("" + BotonSeleccionado(Entrada));

        switch (BotonSeleccionado(Entrada)) {

            case "btnS1":
                btnS1.setBackground(Color.yellow);
                break;
            case "btnF1":
                btnF1.setBackground(Color.yellow);
                break;
            case "btnG1":
                btnG1.setBackground(Color.yellow);
                break;
            case "btnD1":
                btnD1.setBackground(Color.yellow);
                break;
            case "btnA1":
                btnA1.setBackground(Color.yellow);
                break;
            case "btnH1":
                btnH1.setBackground(Color.yellow);
                break;
            case "btnJ1":
                btnJ1.setBackground(Color.yellow);
                break;
            case "btnK1":
                btnK1.setBackground(Color.yellow);
                break;
            case "btnL1":
                btnL1.setBackground(Color.yellow);
                break;
            case "btnN2":
                btnN2.setBackground(Color.yellow);
                break;
            case "btnZ1":
                btnZ1.setBackground(Color.yellow);
                break;
            case "btnX1":
                btnX1.setBackground(Color.yellow);
                break;
            case "btnC1":
                btnC1.setBackground(Color.yellow);
                break;
            case "btnV1":
                btnV1.setBackground(Color.yellow);
                break;
            case "btnB1":
                btnB1.setBackground(Color.yellow);
                break;
            case "btnN1":
                btnN1.setBackground(Color.yellow);
                break;
            case "btnM1":
                btnM1.setBackground(Color.yellow);
                break;
            case "btnQ1":
                btnQ1.setBackground(Color.yellow);
                break;
            case "btnW1":
                btnW1.setBackground(Color.yellow);
                break;
            case "btnE1":
                btnE1.setBackground(Color.yellow);
                break;
            case "btnR1":
                btnR1.setBackground(Color.yellow);
                break;
            case "btnT1":
                btnT1.setBackground(Color.yellow);
                break;
            case "btnY1":
                btnY1.setBackground(Color.yellow);
                break;
            case "btnU1":
                btnU1.setBackground(Color.yellow);
                break;
            case "btnI1":
                btnI1.setBackground(Color.yellow);
                break;
            case "btnO1":
                btnO1.setBackground(Color.yellow);
                break;
            case "btnP1":
                btnP1.setBackground(Color.yellow);
                break;
            case "btnEspacio1":
                btnSpace1.setBackground(Color.yellow);
                break;
        }
        //System.out.println("Key Character: " + evt.getKeyChar() + "; Key Code: " + KeyEvent.getKeyText(evt.getKeyCode()));
    }//GEN-LAST:event_jpanelTecladoKeyPressed

    /*z+
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmjuegoniveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmjuegoniveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmjuegoniveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmjuegoniveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmjuegoniveles(Niveles.NIVEL1).setVisible(true);

            }
        });
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnI1;
    private javax.swing.JButton btnJ1;
    private javax.swing.JButton btnK1;
    private javax.swing.JButton btnL1;
    private javax.swing.JButton btnM1;
    private javax.swing.JButton btnN1;
    private javax.swing.JButton btnN2;
    private javax.swing.JButton btnO1;
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnQ1;
    private javax.swing.JButton btnR1;
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnSpace1;
    private javax.swing.JButton btnT1;
    private javax.swing.JButton btnU1;
    private javax.swing.JButton btnV1;
    private javax.swing.JButton btnW1;
    private javax.swing.JButton btnX1;
    private javax.swing.JButton btnY1;
    private javax.swing.JButton btnZ1;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanelTeclado;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {

    }

    @Override
    public void keyPressed(KeyEvent ke) {

    }

    @Override
    public void keyReleased(KeyEvent ke) {

    }
}
