/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author lfcontreras
 */
public class frmsplash extends javax.swing.JFrame {

    /**
     * Creates new form frmsplash
     */
    public frmsplash() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("../img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblporcentaje = new javax.swing.JLabel();
        jbpcarga = new javax.swing.JProgressBar();
        lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblporcentaje.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblporcentaje.setForeground(new java.awt.Color(0, 0, 153));
        lblporcentaje.setText("99%");
        getContentPane().add(lblporcentaje);
        lblporcentaje.setBounds(260, 400, 46, 32);

        jbpcarga.setForeground(new java.awt.Color(181, 226, 247));
        getContentPane().add(jbpcarga);
        jbpcarga.setBounds(180, 370, 190, 30);

        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/draw_inicial.jpg"))); // NOI18N
        lblimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblimagen.setName(""); // NOI18N
        getContentPane().add(lblimagen);
        lblimagen.setBounds(0, -10, 573, 580);

        setSize(new java.awt.Dimension(573, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmsplash().setVisible(true);
            }
        });
    }
    **/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar jbpcarga;
    private javax.swing.JLabel lblimagen;
    public static javax.swing.JLabel lblporcentaje;
    // End of variables declaration//GEN-END:variables
}
